### ISSUE TITLE
Bug issue with NextJS development: Looping trying to fix TypeScript configuration issue

### ISSUE THREAD

**Issue by hungle816** [clinebot/cline#498] opened 2024-10-10 22:57 UTC
### Which API Provider are you using?

Anthropic

### Which Model are you using?

Claude 3.5 Sonnet

### What happened?

ClaudeDev is getting in a loop with TypeScript and Elints error.

### Steps to reproduce

1. It get trigger as the app is getting built
2. It detects TypeScript error 
3. It try to resolve the issue and keep looping back and get back to the starting point.
4. I believe it is not seeing the terminal. 
5. VSCode on MacOS 15.0.1, it was working fine before 2.0 update

### Relevant API REQUEST output

```shell
I attached the export
```

### Additional context

[cline_task_oct-10-2024_5-52-51-pm.md](https://github.com/user-attachments/files/17335166/cline_task_oct-10-2024_5-52-51-pm.md)

**Comment by saoudrizwan** [comment] 2024-10-11 00:07
It seems macos 15.0.1 has shell integration issues, closing as duplicate of https://github.com/clinebot/cline/issues/484

**Closed by saoudrizwan** 2024-10-11 00:07 UTC
Labels: bug
