### ISSUE TITLE
inspect website tool is not working on Ubuntu 24.4. LTS - the App Armor blocking Chromium known problem.

### ISSUE THREAD

**Issue by m-check1B** [clinebot/cline#438] opened 2024-10-03 06:55 UTC
### Which API Provider are you using?

Anthropic

### Which Model are you using?

Claude 3.5

### What happened?

Could not take the screenshot. Could not resolve on Ubuntu 24.4. LTS but this problem is NOT PRESENT on 22.4.LTS where it works just fine. I suggest putting this note to install docs.

### Steps to reproduce

1.
2.
3.

**Comment by saoudrizwan** [comment] 2024-10-11 02:05
Thank you for the details, I will look into this and see if there's a workaround. Closing as duplicate of https://github.com/clinebot/cline/issues/475

**Closed by saoudrizwan** 2024-10-11 02:05 UTC
Labels: bug
