### ISSUE TITLE
o1-preview  'messages[0].role' does not support 'system' with this model.

### ISSUE THREAD

**Issue by araimbekoff** [clinebot/cline#434] opened 2024-10-02 10:27 UTC
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

o1-preview

### What happened?

400 Unsupported value: 'messages[0].role' does not support 'system' with this model.

### Steps to reproduce

at any request

![Uploading image.png…]()

**Comment by araimbekoff** [comment] 2024-10-02 10:29
![image](https://github.com/user-attachments/assets/06c2e858-3b9f-48cf-84b8-64803895a90a)

**Comment by saoudrizwan** [comment] 2024-10-11 02:41
Closing as duplicate of https://github.com/clinebot/cline/issues/445 will get this fixed asap!

**Closed by saoudrizwan** 2024-10-11 02:41 UTC
Labels: bug

**Comment by araimbekoff** [comment] 2024-11-16 16:20
Hi there!
this api doesn't work with OpenAI Compatible (
Help please
