### ISSUE TITLE
Can’t work on any other projects while working with Claude Dev

### ISSUE THREAD

**Issue by atljoseph** [clinebot/cline#428] opened 2024-10-01 12:42 UTC
### Which API Provider are you using?

Anthropic

### Which Model are you using?

Claude 3.5 sonnet, but it doesn’t matter about the model.

### What happened?

The extension works and works well. I’m not complaining about that. I am complaining about _the inability to use VSCode for any other intensive tasks while also using Claude Dev._ 

If I give the extension a task, and then move on to take care of a manual code change on completely unrelated files, then I always get interrupted when Claude dev opens the file diff. I hate interruptions. Interruptions mean context switching. 

It often interrupts me when I’m in the middle of some complicated keyboard shortcut. While this seems mostly harmless, it is in fact distracting, and it steals the attention of users away from their chosen manual task. In the end, it claims to save time and allow for easier multitasking, but in reality, it gets in there and distracts me from all tasks. 

Can you make this extension not be so greedy in terms of user attention? When a diff for a file is opened, please don’t make it gain the full focus of VSCode. Please be respectful to users… humans… people. Humans don’t work for AI, after all. Isn’t it the other way around. 

Make the extension less distracting so that devs can actually use it in their workflow instead of Claude dev becoming the whole workflow. 

### Steps to reproduce

1. Give Claude dev a task
2. Immediately work on other code in same window
3. Get distracted while typing on other code by “autonomous” Claude dev opening diff for task
4. Get annoyed because confused, distracted, and now have to go fix stuff that wasn’t broken. 
5. Curse Claude dev for not being respectful with human attention. 

### Additional context

Ask and the question will be answered.

**Comment by tsdevau** [comment] 2024-10-01 21:00
I had previously raised this (but far less detailed) issue in #339.

**Comment by saoudrizwan** [comment] 2024-10-11 02:11
I am currently working on Cline being able to stream to editors in the background instead of having to keep the tab he's modifying active. But outside of that it's hard to know what a version of the extension looks like where it's working in the background. I suggest using a second window for working on something else? Closing as duplicate of @tsdevau's request

**Closed by saoudrizwan** 2024-10-11 02:11 UTC
Labels: bug
